package com.zwyl.mapper;

import com.zwyl.model.SsAppUpdateVersion;

public interface SsAppUpdateVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_app_update_version
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_app_update_version
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    int insert(SsAppUpdateVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_app_update_version
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    int insertSelective(SsAppUpdateVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_app_update_version
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    SsAppUpdateVersion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_app_update_version
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    int updateByPrimaryKeySelective(SsAppUpdateVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_app_update_version
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    int updateByPrimaryKey(SsAppUpdateVersion record);
}