package com.zwyl.mapper;

import com.zwyl.model.Test;

public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Sat Feb 10 17:50:13 CST 2018
     */
    int insert(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Sat Feb 10 17:50:13 CST 2018
     */
    int insertSelective(Test record);
}