package com.zwyl.model;

public class SsAppUpdateVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_app_update_version.id
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_app_update_version.latest_version
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    private Boolean latestVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_app_update_version.update_type
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    private Integer updateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_app_update_version.latest_version_code
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    private String latestVersionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_app_update_version.latest_version_name
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    private String latestVersionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_app_update_version.download_address
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    private String downloadAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_app_update_version.update_content
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    private String updateContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_app_update_version.device_type
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    private String deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_app_update_version.other
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_app_update_version.id
     *
     * @return the value of ss_app_update_version.id
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_app_update_version.id
     *
     * @param id the value for ss_app_update_version.id
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_app_update_version.latest_version
     *
     * @return the value of ss_app_update_version.latest_version
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public Boolean getLatestVersion() {
        return latestVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_app_update_version.latest_version
     *
     * @param latestVersion the value for ss_app_update_version.latest_version
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public void setLatestVersion(Boolean latestVersion) {
        this.latestVersion = latestVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_app_update_version.update_type
     *
     * @return the value of ss_app_update_version.update_type
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public Integer getUpdateType() {
        return updateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_app_update_version.update_type
     *
     * @param updateType the value for ss_app_update_version.update_type
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public void setUpdateType(Integer updateType) {
        this.updateType = updateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_app_update_version.latest_version_code
     *
     * @return the value of ss_app_update_version.latest_version_code
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public String getLatestVersionCode() {
        return latestVersionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_app_update_version.latest_version_code
     *
     * @param latestVersionCode the value for ss_app_update_version.latest_version_code
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public void setLatestVersionCode(String latestVersionCode) {
        this.latestVersionCode = latestVersionCode == null ? null : latestVersionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_app_update_version.latest_version_name
     *
     * @return the value of ss_app_update_version.latest_version_name
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public String getLatestVersionName() {
        return latestVersionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_app_update_version.latest_version_name
     *
     * @param latestVersionName the value for ss_app_update_version.latest_version_name
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public void setLatestVersionName(String latestVersionName) {
        this.latestVersionName = latestVersionName == null ? null : latestVersionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_app_update_version.download_address
     *
     * @return the value of ss_app_update_version.download_address
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public String getDownloadAddress() {
        return downloadAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_app_update_version.download_address
     *
     * @param downloadAddress the value for ss_app_update_version.download_address
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public void setDownloadAddress(String downloadAddress) {
        this.downloadAddress = downloadAddress == null ? null : downloadAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_app_update_version.update_content
     *
     * @return the value of ss_app_update_version.update_content
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public String getUpdateContent() {
        return updateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_app_update_version.update_content
     *
     * @param updateContent the value for ss_app_update_version.update_content
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public void setUpdateContent(String updateContent) {
        this.updateContent = updateContent == null ? null : updateContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_app_update_version.device_type
     *
     * @return the value of ss_app_update_version.device_type
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_app_update_version.device_type
     *
     * @param deviceType the value for ss_app_update_version.device_type
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_app_update_version.other
     *
     * @return the value of ss_app_update_version.other
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_app_update_version.other
     *
     * @param other the value for ss_app_update_version.other
     *
     * @mbggenerated Wed May 01 23:03:07 CST 2019
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}