package com.zwyl.model;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.t4
     *
     * @mbggenerated Sat Feb 10 17:50:13 CST 2018
     */
    private String t4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.t3
     *
     * @mbggenerated Sat Feb 10 17:50:13 CST 2018
     */
    private String t3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.t2
     *
     * @mbggenerated Sat Feb 10 17:50:13 CST 2018
     */
    private String t2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.t1
     *
     * @mbggenerated Sat Feb 10 17:50:13 CST 2018
     */
    private String t1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.t4
     *
     * @return the value of test.t4
     *
     * @mbggenerated Sat Feb 10 17:50:13 CST 2018
     */
    public String getT4() {
        return t4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.t4
     *
     * @param t4 the value for test.t4
     *
     * @mbggenerated Sat Feb 10 17:50:13 CST 2018
     */
    public void setT4(String t4) {
        this.t4 = t4 == null ? null : t4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.t3
     *
     * @return the value of test.t3
     *
     * @mbggenerated Sat Feb 10 17:50:13 CST 2018
     */
    public String getT3() {
        return t3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.t3
     *
     * @param t3 the value for test.t3
     *
     * @mbggenerated Sat Feb 10 17:50:13 CST 2018
     */
    public void setT3(String t3) {
        this.t3 = t3 == null ? null : t3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.t2
     *
     * @return the value of test.t2
     *
     * @mbggenerated Sat Feb 10 17:50:13 CST 2018
     */
    public String getT2() {
        return t2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.t2
     *
     * @param t2 the value for test.t2
     *
     * @mbggenerated Sat Feb 10 17:50:13 CST 2018
     */
    public void setT2(String t2) {
        this.t2 = t2 == null ? null : t2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.t1
     *
     * @return the value of test.t1
     *
     * @mbggenerated Sat Feb 10 17:50:13 CST 2018
     */
    public String getT1() {
        return t1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.t1
     *
     * @param t1 the value for test.t1
     *
     * @mbggenerated Sat Feb 10 17:50:13 CST 2018
     */
    public void setT1(String t1) {
        this.t1 = t1 == null ? null : t1.trim();
    }
}